name       : serf
version    : 1.3.8
release    : 2
source     :
    - https://archive.apache.org/dist/serf/serf-1.3.8.tar.bz2 : e0500be065dbbce490449837bb2ab624e46d64fc0b090474d9acaa87c82b2590
license    : Apache-2.0
summary    : The serf library is a high performance C-based HTTP client library
description: |
    The serf library is a high performance C-based HTTP client library
builddeps  :
    - pkgconfig(apr-1)
    - pkgconfig(apr-util-1)
    - pkgconfig(krb5)
    - pkgconfig(openssl)
    - libtool
    - scons
setup      : |
    %patch -p1 < $pkgfiles/serf-1.3.x-fix-comment-style.patch
    %patch -p1 < $pkgfiles/serf-1.3.x-fix-deflate-buckets-test.patch
build      : |
    scons PREFIX=/usr
install    : |
    scons PREFIX="$installdir/usr" LIBDIR="$installdir/%libdir%" install
    rm -rf $installdir/%libdir%/*.a
