name       : serf
version    : 1.3.9
release    : 9
source     :
    - https://github.com/apache/serf/archive/1.3.9.tar.gz : ebeb4904692e68469de7fdedf99f1fc102d3fc922c9bb811231c7ff7395b9c9c
license    : Apache-2.0
component  : programming
summary    : The serf library is a high performance C-based HTTP client library
description: |
    The serf library is a high performance C-based HTTP client library
builddeps  :
    - pkgconfig(apr-1)
    - pkgconfig(apr-util-1)
    - pkgconfig(krb5)
    - libtool
    - openldap-devel
    - scons
build      : |
    scons %JOBS% PREFIX=/usr
install    : |
    scons PREFIX="$installdir/usr" LIBDIR="$installdir/%libdir%" install
    rm -rf $installdir/%libdir%/*.a
