name       : serf
version    : 1.3.9
release    : 8
source     :
    - git|https://github.com/apache/serf.git : 1cb2ab783fb7182a7d5db64d428be30b6d779a90
license    : Apache-2.0
component  : programming
summary    : The serf library is a high performance C-based HTTP client library
description: |
    The serf library is a high performance C-based HTTP client library
builddeps  :
    - pkgconfig(apr-1)
    - pkgconfig(apr-util-1)
    - pkgconfig(krb5)
    - libtool
    - openldap-devel
    - scons
build      : |
    scons PREFIX=/usr
install    : |
    scons PREFIX="$installdir/usr" LIBDIR="$installdir/%libdir%" install
    rm -rf $installdir/%libdir%/*.a
